AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda

Resources:

  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: helloWorld.handler
      CodeUri: ./Lambda
      Runtime: nodejs10.x
      AutoPublishAlias: dev
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      DeploymentPreference:
          Type: AllAtOnce
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Events:
        HelloWorldAPI:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          REGION: us-west-1
